#
# SPDX-FileCopyrightText: Copyright © 2023 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Fabio Fehr <fabio.fehr@idiap.ch>, Melika Behjati <melika.behjati@idiap.ch>
#
# SPDX-License-Identifier: GPL-3.0-only
#

name: nvib_sa
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.11 # Free BSD - https://www.python.org/
  - pytorch::pytorch=2.0.0 # BSD3 - https://pytorch.org/
  - pytorch::pytorch-cuda=11.8 # BSD3 - https://pytorch.org/
  - nvidia::cuda=11.8 # MIT - https://docs.nvidia.com/cuda/eula/index.html
  - pip # MIT - https://github.com/pypa/pip
  - matplotlib=3.7.0 # BSD - https://github.com/pypa/pip
  - transformers=4.29.2 # apache2.0 - https://pypi.org/project/transformers/
  - datasets # Apache 2.0 - https://pypi.org/project/datasets/
  - pyarrow>=3.0.0 # Apache - https://arrow.apache.org/docs/python/index.html
  - wandb # MIT https://wandb.ai/site
  - pytorch-lightning=1.9.4 # Apache License 2.0 - https://pytorch-lightning.readthedocs.io/en/stable/
  - pytest # MIT - https://docs.pytest.org/en/7.1.x/index.html
  - python-dotenv # BSD-3-Clause - https://pypi.org/project/python-dotenv/
  - nltk #  Apache 2.0 License - https://www.nltk.org/index.html
  - evaluate # apache 2.0 - https://github.com/huggingface
  - sacrebleu # Apache 2.0 - https://pypi.org/project/sacrebleu/
  - plotly # MIT license - https://plotly.com/python/getting-started/
  - python-kaleido # MIT license - https://pypi.org/project/kaleido/
  - seaborn # BSD-3-Clause - https://seaborn.pydata.org/index.html
  - pip:
    - ../nvib/. # GPLv3

